AzureCR/azure-cli-extensions

- src/acrcssc/azext_acrcssc/templates/task/cssc_sbom_image.yaml
Work pending, saving for future development
> move cssc_sbom branch from personal repo to AzureCR

- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
- src/acrcssc/azext_acrcssc/helper/_workflow_status.py
- src/acrcssc/setup.py
To make the output of the `list` command easier to read, renamed `skipped_patch_reason` to `patch_skipped_reason`.
```
az acr supply-chain workflow list ...
Total images: 14
[
{
"image": "import:dotnetapp-manual",
"last_patched_image": "import:dotnetapp-manual-1",
"patch_date": "---Not Available---",
"patch_skipped_reason": "no vulnerability found in the image import:dotnetapp-manual-1",
"patch_status": "Skipped",
"patch_task_ID": "---Not Available---",
"scan_date": "2025-01-23T17:56:27.412952+00:00",
"scan_status": "Succeeded",
"scan_task_ID": "dt23a",
"workflow_type": "continuouspatchv1"
},
...
```
> fix(cssc): 31038071 Rename "skipped_patch_reason" to "patch_skipped_reason" to bring all patching props together

- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
- src/acrcssc/azext_acrcssc/helper/_workflow_status.py
- src/acrcssc/setup.py
'Canceled' state was originally mapped as part of the 'Failed' state in the `WorkflowTaskState` enum.
This change makes the 'Canceled' state so it maps to ACR Task's state.
Since this is part of the enum, the help text and the `--run-status` option does not require additional changes
```
az acr supply-chain workflow list ... --run-status canceled
Total images: 5
[
{
"image": "import:dotnetapp-manual",
"last_patched_image": "import:dotnetapp-manual-1",
"patch_date": "---Not Available---",
"patch_status": "Unknown",
"patch_task_ID": "---Not Available---",
"scan_date": "2025-01-23T22:36:54.223026+00:00",
"scan_status": "Canceled",
"scan_task_ID": "dt23q",
"workflow_type": "continuouspatchv1"
},
...
```
```
$  az acr supply-chain workflow list  -h
...
--run-status                   : Status …
```
> fix(cssc): 30943055 add a 'canceled' state for scan and patching workflows

- src/acrcssc/azext_acrcssc/templates/task/cssc_trigger_workflow.yaml
- src/acrcssc/azext_acrcssc/templates/tmp_dry_run_template.yaml
Added a max limit of 100 for continuous patching addressing below WI:
https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/31125505
> fix(cssc): added a max limit of 100 images allowed for continuous patching

- src/acrcssc/azext_acrcssc/helper/_workflow_status.py
- src/acrcssc/azext_acrcssc/templates/task/cssc_patch_image.yaml
- src/acrcssc/azext_acrcssc/templates/task/cssc_scan_image.yaml
- Updated print command statements
- Removed the step to attach the vulnerability scan report to the image and list output file
- Removed comments from the yaml
- Increased delay between retries
> fix(cssc): task files cleanup

- src/acrcssc/azext_acrcssc/templates/task/cssc_trigger_workflow.yaml
Idea here is to trickle the scan task scheduling in a batch of 10 every 30 seconds instead of scheduling all at once.
This is to avoid overwhelming the tasks infrastructure.
We haven't seen any throttling issues so far with tasks; however, this is a proactive measure to avoid any.
> feat(cssc): Enhance Trigger Task to schedule image scans in batches of 10

- src/acrcssc/azext_acrcssc/templates/task/cssc_patch_image.yaml
- src/acrcssc/azext_acrcssc/templates/task/cssc_scan_image.yaml
- src/acrcssc/azext_acrcssc/templates/task/cssc_trigger_workflow.yaml
- src/acrcssc/azext_acrcssc/templates/tmp_dry_run_template.yaml
Updated cssc image to use source policy to fix docker throttling issue during tooling image pull for DPKG based images.
This was a blocker for Public Preview.
For Ubuntu based images, verified that the tooling image is now pulled from MCR instead of docker:
For Debian, this will start working once the OSS upstream image PR completes.
> feat(cssc): 31084399 cssc image update to use source policy

- src/acrcssc/azext_acrcssc/templates/task/cssc_patch_image.yaml
Changes to use the cached buildkit image from buildhost instead of docker
With this, buildkitd step doesn't pull anymore from docker
Verified that this change works in Canary.
For this to work in all regions, Feb Task deployment should complete in all regions which is by early next week.
> feat(cssc): 31482353 changes to pull buildkit from cached image in buildhost

- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
To avoid hitting the issue around "Discriminator type is absent or null, use base class TaskStepProperties" when the Task update is performed as a LongRunningOperation, it is better to remove the wrapper.
This keeps functionality intact as the operation will still be done, but is not tracked by the poller
> fix(cssc): 31670277 Remove LongRunningOperation wrapper for task updates

- src/acrcssc/azext_acrcssc/_validators.py
- src/acrcssc/azext_acrcssc/cssc.py
During dry-run, we inform the user if images matching their configuration = 0.
However, currently, during actual create/update, this information is lost.
With this fix, I am basically matching up the dry-run and actual run logs by relaying this information to the user.
Intentionally not blocking the create/update operation - for the scenarios when user wants to create the patching workflow first and later wants to push relevant images.
Bug - https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/31694219/?view=edit
Behavior after fix on Update...
Behavior after fix on Create..
> fix(cssc): 31694219 inform user when images matching their configuration are 0

- src/acrcssc/HISTORY.rst
- src/acrcssc/README.rst
- src/acrcssc/azext_acrcssc/_params.py
- src/acrcssc/azext_acrcssc/cssc.py
- src/acrcssc/azext_acrcssc/helper/_constants.py
- src/acrcssc/azext_acrcssc/helper/_ociartifactoperations.py
- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
- src/acrcssc/azext_acrcssc/helper/_workflow_status.py
- src/acrcssc/azext_acrcssc/tests/latest/config/scenario_test_config.json
- src/acrcssc/azext_acrcssc/tests/latest/recordings/test_acrcssc_workflow.yaml
- src/acrcssc/azext_acrcssc/tests/latest/test_cssc.py
- src/acrcssc/azext_acrcssc/tests/latest/test_cssc_scenario.py
- src/acrcssc/azext_acrcssc/tests/latest/test_helper_taskoperations.py
- src/acrcssc/setup.py
- Add ScenarioTest for the extension and the recording
- Fix remaining style and lint issues
- Fix README file to reflect basic usage
- Fix HISTORY and setup.py to have the final release version for private preview
> test(cssc): 30926545 add Scenario test for extension, fix style issues (2/n)

- src/acrcssc/azext_acrcssc/helper/_constants.py
- src/acrcssc/azext_acrcssc/tests/latest/test_validators.py
Currently, no validation error is thrown when repositories are empty or repeated in configuration file.
Bug - https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/31695069/?view=edit
This PR fixes the issue by enhancing schema validation for repositories and updating the tests to test for this scenario.
> fix(cssc): 31695069 Enhanced repositories schema validation + added tests

- src/acrcssc/azext_acrcssc/cssc.py
- src/acrcssc/azext_acrcssc/helper/_constants.py
- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
- src/acrcssc/azext_acrcssc/tests/latest/test_helper_taskoperations.py
This PR adds a check to ensure that the cssc tasks exist before calling the list command. It also displays that the list command is executed for the last n days. Updated tests as well.
With this, below 2 bugs are addressed:
1. https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/31694510/?view=edit
Before Fix: 
After Fix:
2. https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/31694600/?view=edit
After Fix: added a line to indicate list executed for last n days:
> fix(cssc): 31694510, 31694600 Check for existence of cssc tasks before calling list command + enhance log message

- src/acrcssc/azext_acrcssc/_validators.py
- src/acrcssc/azext_acrcssc/cssc.py
- src/acrcssc/azext_acrcssc/tests/latest/test_validators.py
Added validation to ensure that the `--dryrun` and `--run-immediately` options cannot be used together both during create and update.
Also added unit tests for this scenario to ensure the validation works as expected.
Bug - https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/31694592/?view=edit
After fix:
> fix(cssc): 31694592 Added validations to ensure dry run and run immediately options are mutually exclusive

- src/acrcssc/azext_acrcssc/_validators.py
- src/acrcssc/azext_acrcssc/cssc.py
- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
- src/acrcssc/azext_acrcssc/helper/_workflow_status.py
To retrieve task logs class `WorkflowTaskStatus` uses a Poller to wait for a task run to finish before attempting to download the logs. This is only done during image limit check or when the `--dry-run` option is used during the `create` and `update` commands. Since this is a remote call there is a chance that we never get a response.
This PR adds a 10-minute timeout to the Poller. In case the timeout is reached, the required message is logged, and the attempt will be done to retrieve the logs if there are any to allow the operation to continue.
In case of a timeout during `create` or `update` the command will not block in case the image limit check could not be performed, to allow for a better user experience. In case the image limit is reached, the user will be informed via the trigger …
> fix(cssc): 31731403 Allow generate_logs poller to timeout

- src/acrcssc/azext_acrcssc/templates/arm/CSSC-AutoImagePatching-encodedtasks.json
Change role assignment during deployment from 'Contributor' to 'Container Registry Tasks Contributor' to trigger and scan tasks during deployment. Reduce access given to the CSSC tasks.
For the new role assignment to take effect the tasks have to be redeployed.
> feat(cssc): 31807191 change role assignment for CSSC tasks to 'Container Registry Tasks Contributor'

- src/acrcssc/azext_acrcssc/helper/_ociartifactoperations.py
This change is only to add check for empty token.
A following PR will be made to update the oras package. Since there are substantial changes to the client usage.
Adding a centralized check for every token we retrieve from the registry and improve on error logging
> fix(cssc): 31670352 add check for empty token for authentication (1/n)

- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
- src/acrcssc/azext_acrcssc/helper/_workflow_status.py
- src/acrcssc/azext_acrcssc/tests/latest/test_cssc.py
- src/acrcssc/azext_acrcssc/tests/latest/test_helper_taskoperations.py
- src/acrcssc/azext_acrcssc/tests/latest/test_workflow_status.py
Fix filtering on the `list` command by `--run-status` to make it correct once again.
Now the `--run-status` will filter the image status depending on the final status of both the scan and patch instead of only one of them. Meaning that for an image to be marked as `FAILED` scan or patch have to be `FAILED`, for an image to be marked as `SUCCEEDED` both scan and patch have to be `SUCCEEDED` or `SKIPPED` as that is treated as a successful execution, and for an image to be marked as `SKIPPED` the scan has to be `SUCCEEDED` and the patch has to be `SKIPPED`.
This PR also includes a unit test to catch issues with the filtering.
In addition, includes fixes for unit tests that are run without azure credentials, adding the required mocks to avoid that dependency.
Some example output:
```
$ az acr …
```
> fix(cssc): 31646926 fix 'list' command filtering by '--run-status'

- src/acrcssc/azext_acrcssc/helper/_ociartifactoperations.py
- src/acrcssc/setup.py
This change is a continuation of the changes in [PR 39](https://github.com/AzureCR/azure-cli-extensions/pull/39)
Updates the `oras` packages to 0.2.25 to use a more recent version of the package to avoid the "empty token" error when authenticating to the registry.
> fix(cssc): 31670352 Upgrade oras-py package to use new auth flow 2/n

- src/acrcssc/azext_acrcssc/_validators.py
- src/acrcssc/azext_acrcssc/helper/_constants.py
- src/acrcssc/azext_acrcssc/helper/_deployment.py
- src/acrcssc/azext_acrcssc/helper/_ociartifactoperations.py
- src/acrcssc/azext_acrcssc/helper/_taskoperations.py
- src/acrcssc/azext_acrcssc/helper/_utility.py
- src/acrcssc/azext_acrcssc/helper/_workflow_status.py
- src/acrcssc/azext_acrcssc/tests/latest/test_helper_taskoperations.py
- src/acrcssc/azext_acrcssc/tests/latest/test_validators.py
Second wave of PR comments for https://github.com/Azure/azure-cli-extensions/pull/8530
Fix remaining open comments on public PR until 04/16/25
Test, style and linter are clean
> fix(cssc): 31250186 address partial comments in public repo PR 20250416

- src/acrcssc/HISTORY.rst
- src/acrcssc/azext_acrcssc/_params.py
- Fix versioning used in HISTORY to reflect final version used in preview (1.0.0b1)
- change resource group parameter to use resource_group_name_type from azure.cli.core.commands.parameters
> fix(cssc): 31250186 address comments on versioning #8690
